// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * ARE (Area) files are GFF-based format files that store static area information including
 * lighting, fog, grass, weather, script hooks, and map data. ARE files use the GFF (Generic File Format)
 * binary structure with file type signature "ARE ".
 * 
 * This format inherits the complete GFF structure from gff.ksy and adds ARE-specific
 * validation and documentation.
 * 
 * ARE Root Struct Fields (Common):
 * - "Tag" (String): Unique area identifier
 * - "Name" (LocalizedString): Area display name
 * - "SunAmbientColor", "SunDiffuseColor" (UInt32): Lighting colors (BGR format)
 * - "SunFogOn", "SunFogNear", "SunFogFar", "SunFogColor": Fog settings
 * - "Grass_*": Grass rendering properties
 * - "OnEnter", "OnExit", "OnHeartbeat", "OnUserDefined": Script hooks (ResRef)
 * - "Map" (Struct): Minimap coordinate mapping
 * - "Rooms" (List): Audio zones and weather regions
 * 
 * KotOR 2 adds weather fields:
 * - "ChanceRain", "ChanceSnow", "ChanceLightning" (Int32)
 * - "Dirty*" fields for dust particle effects
 * 
 * References:
 * - https://github.com/OldRepublicDevs/PyKotor/wiki/GFF-ARE.md
 * - https://github.com/OldRepublicDevs/PyKotor/wiki/GFF-File-Format.md
 * - https://github.com/OldRepublicDevs/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/resource/generics/are.py
 * - https://github.com/seedhartha/reone/blob/master/src/libs/resource/parser/gff/are.cpp
 */
type Are struct {
	GffData *Gff
	_io *kaitai.Stream
	_root *Are
	_parent kaitai.Struct
	_f_fileTypeValid bool
	fileTypeValid bool
	_f_rootStructResolved bool
	rootStructResolved *Gff_ResolvedStruct
	_f_versionValid bool
	versionValid bool
}
func NewAre() *Are {
	return &Are{
	}
}

func (this Are) IO_() *kaitai.Stream {
	return this._io
}

func (this *Are) Read(io *kaitai.Stream, parent kaitai.Struct, root *Are) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewGff()
	err = tmp1.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.GffData = tmp1
	return err
}

/**
 * Validates that this is an ARE file (file type must be "ARE ")
 */
func (this *Are) FileTypeValid() (v bool, err error) {
	if (this._f_fileTypeValid) {
		return this.fileTypeValid, nil
	}
	this._f_fileTypeValid = true
	this.fileTypeValid = bool(this.GffData.Header.FileType == "ARE ")
	return this.fileTypeValid, nil
}

/**
 * Convenience access to the decoded GFF root struct (struct_array[0]).
 * Use this to iterate all resolved fields (label + typed value), including:
 * "Tag", "Name", "AlphaTest", "Map" (struct), "Rooms" (list), and all KotOR2/deprecated keys.
 */
func (this *Are) RootStructResolved() (v *Gff_ResolvedStruct, err error) {
	if (this._f_rootStructResolved) {
		return this.rootStructResolved, nil
	}
	this._f_rootStructResolved = true
	tmp2, err := this.GffData.RootStructResolved()
	if err != nil {
		return nil, err
	}
	this.rootStructResolved = tmp2
	return this.rootStructResolved, nil
}

/**
 * Validates GFF version is supported
 */
func (this *Are) VersionValid() (v bool, err error) {
	if (this._f_versionValid) {
		return this.versionValid, nil
	}
	this._f_versionValid = true
	this.versionValid = bool( ((this.GffData.Header.FileVersion == "V3.2") || (this.GffData.Header.FileVersion == "V3.3") || (this.GffData.Header.FileVersion == "V4.0") || (this.GffData.Header.FileVersion == "V4.1")) )
	return this.versionValid, nil
}

/**
 * Complete GFF structure. ARE files use standard GFF format with "ARE " file type.
 * Access via: gff_data.header, gff_data.struct_array, gff_data.field_array, etc.
 */
