// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * BZF (BioWare Zipped File) files are LZMA-compressed BIF files used primarily in iOS
 * (and maybe Android) ports of KotOR. The BZF header contains "BZF " + "V1.0", followed
 * by LZMA-compressed BIF data. Decompression reveals a standard BIF structure.
 * 
 * Format Structure:
 * - Header (8 bytes): File type signature "BZF " and version "V1.0"
 * - Compressed Data: LZMA-compressed BIF file data
 * 
 * After decompression, the data follows the standard BIF format structure.
 * 
 * References:
 * - https://github.com/OldRepublicDevs/PyKotor/wiki/BIF-File-Format.md - BZF compression section
 * - BIF.ksy - Standard BIF format (decompressed BZF data matches this)
 */
type Bzf struct {
	FileType string
	Version string
	CompressedData []uint8
	_io *kaitai.Stream
	_root *Bzf
	_parent kaitai.Struct
}
func NewBzf() *Bzf {
	return &Bzf{
	}
}

func (this Bzf) IO_() *kaitai.Stream {
	return this._io
}

func (this *Bzf) Read(io *kaitai.Stream, parent kaitai.Struct, root *Bzf) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.FileType = string(tmp1)
	if !(this.FileType == "BZF ") {
		return kaitai.NewValidationNotEqualError("BZF ", this.FileType, this._io, "/seq/0")
	}
	tmp2, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp2 = tmp2
	this.Version = string(tmp2)
	if !(this.Version == "V1.0") {
		return kaitai.NewValidationNotEqualError("V1.0", this.Version, this._io, "/seq/1")
	}
	for i := 0;; i++ {
		tmp3, err := this._io.EOF()
		if err != nil {
			return err
		}
		if tmp3 {
			break
		}
		tmp4, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.CompressedData = append(this.CompressedData, tmp4)
	}
	return err
}

/**
 * File type signature. Must be "BZF " for compressed BIF files.
 */

/**
 * File format version. Always "V1.0" for BZF files.
 */

/**
 * LZMA-compressed BIF file data.
 * This data must be decompressed using LZMA algorithm to obtain the standard BIF structure.
 * After decompression, the data can be parsed using the BIF format definition.
 */
