// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * CNV (Conversation) files are GFF-based format files that store conversation trees with entries, replies,
 * links, and conversation metadata. CNV files use the GFF (Generic File Format) binary structure
 * with file type signature "CNV ".
 * 
 * This format inherits the complete GFF structure from gff.ksy and adds CNV-specific
 * validation and documentation.
 * 
 * CNV files are used by Eclipse Engine games (Dragon Age Origins, Dragon Age 2, Mass Effect, Mass Effect 2).
 * They are similar to DLG files used by Odyssey and Aurora engines but adapted for Eclipse's conversation system.
 * 
 * CNV Root Struct Fields:
 * - NumWords (Int32): Word count for conversation
 * - Skippable (UInt8): Whether conversation can be skipped
 * - ConversationType (Int32): Conversation type identifier
 * - EntryList (List): NPC dialogue lines (CNVEntry structs)
 * - ReplyList (List): Player response options (CNVReply structs)
 * - StartingList (List): Entry points (CNVLink structs)
 * - StuntList (List): Special animations (CNVStunt structs)
 * 
 * Each Entry/Reply contains:
 * - Text (LocalizedString): Dialogue text
 * - Script (ResRef): Conditional/action scripts
 * - Camera settings, animations, links to other nodes
 * 
 * References:
 * - https://github.com/OldRepublicDevs/PyKotor/wiki/GFF-CNV.md
 * - https://github.com/OldRepublicDevs/PyKotor/wiki/GFF-File-Format.md
 */
type Cnv struct {
	GffData *Gff
	_io *kaitai.Stream
	_root *Cnv
	_parent kaitai.Struct
	_f_fileTypeValid bool
	fileTypeValid bool
	_f_versionValid bool
	versionValid bool
}
func NewCnv() *Cnv {
	return &Cnv{
	}
}

func (this Cnv) IO_() *kaitai.Stream {
	return this._io
}

func (this *Cnv) Read(io *kaitai.Stream, parent kaitai.Struct, root *Cnv) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewGff()
	err = tmp1.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.GffData = tmp1
	return err
}

/**
 * Validates that this is a CNV file (file type must be "CNV ")
 */
func (this *Cnv) FileTypeValid() (v bool, err error) {
	if (this._f_fileTypeValid) {
		return this.fileTypeValid, nil
	}
	this._f_fileTypeValid = true
	this.fileTypeValid = bool(this.GffData.Header.FileType == "CNV ")
	return this.fileTypeValid, nil
}

/**
 * Validates GFF version is supported
 */
func (this *Cnv) VersionValid() (v bool, err error) {
	if (this._f_versionValid) {
		return this.versionValid, nil
	}
	this._f_versionValid = true
	this.versionValid = bool( ((this.GffData.Header.FileVersion == "V3.2") || (this.GffData.Header.FileVersion == "V3.3") || (this.GffData.Header.FileVersion == "V4.0") || (this.GffData.Header.FileVersion == "V4.1")) )
	return this.versionValid, nil
}

/**
 * Complete GFF structure. CNV files use standard GFF format with "CNV " file type.
 * Access via: gff_data.header, gff_data.struct_array, gff_data.field_array, etc.
 */
