// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * DLG (Dialogue) files are GFF-based format files that store conversation trees with entries, replies,
 * links, and conversation metadata for Odyssey and Aurora engines.
 * 
 * This format inherits the complete GFF structure from gff.ksy and adds DLG-specific
 * validation and documentation.
 * 
 * DLG files contain:
 * - Root struct with conversation metadata (NumWords, Skippable, ConversationType, etc.)
 * - EntryList: Array of dialogue entries (NPC lines)
 * - ReplyList: Array of reply options (player responses)
 * - StartingList: Array of entry points into conversation tree
 * - StuntList: Array of cutscene/animation sequences
 * 
 * References:
 * - https://github.com/OldRepublicDevs/PyKotor/wiki/GFF-DLG.md
 * - https://github.com/OldRepublicDevs/PyKotor/tree/master/Libraries/PyKotor/src/pykotor/resource/generics/dlg/
 */
type Dlg struct {
	GffData *Gff
	_io *kaitai.Stream
	_root *Dlg
	_parent kaitai.Struct
	_f_fileTypeValid bool
	fileTypeValid bool
	_f_versionValid bool
	versionValid bool
}
func NewDlg() *Dlg {
	return &Dlg{
	}
}

func (this Dlg) IO_() *kaitai.Stream {
	return this._io
}

func (this *Dlg) Read(io *kaitai.Stream, parent kaitai.Struct, root *Dlg) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewGff()
	err = tmp1.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.GffData = tmp1
	return err
}

/**
 * Validates DLG file type
 */
func (this *Dlg) FileTypeValid() (v bool, err error) {
	if (this._f_fileTypeValid) {
		return this.fileTypeValid, nil
	}
	this._f_fileTypeValid = true
	this.fileTypeValid = bool(this.GffData.Header.FileType == "DLG ")
	return this.fileTypeValid, nil
}

/**
 * Validates GFF version
 */
func (this *Dlg) VersionValid() (v bool, err error) {
	if (this._f_versionValid) {
		return this.versionValid, nil
	}
	this._f_versionValid = true
	this.versionValid = bool( ((this.GffData.Header.FileVersion == "V3.2") || (this.GffData.Header.FileVersion == "V3.3") || (this.GffData.Header.FileVersion == "V4.0") || (this.GffData.Header.FileVersion == "V4.1")) )
	return this.versionValid, nil
}

/**
 * Complete GFF structure with "DLG " file type
 */
