// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * FAC (Faction) files are GFF-based format files that store faction relationships,
 * reputation values, and faction metadata.
 * 
 * This format inherits the complete GFF structure from gff.ksy and adds FAC-specific
 * validation and documentation.
 * 
 * FAC Root Struct Fields:
 * - FactionName (String): Faction identifier
 * - FactionParentID (UInt16): Parent faction ID
 * - FactionGlobal (UInt16): Global faction flag
 * - RepList (List): Reputation values with other factions
 *   - FactionID (UInt32): Target faction ID
 *   - FactionRep (UInt32): Reputation value (0-100)
 * 
 * References:
 * - https://github.com/OldRepublicDevs/PyKotor/wiki/GFF-FAC.md
 * - https://github.com/OldRepublicDevs/PyKotor/wiki/GFF-File-Format.md
 * - https://github.com/OldRepublicDevs/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/resource/generics/fac.py
 */
type Fac struct {
	GffData *Gff
	_io *kaitai.Stream
	_root *Fac
	_parent kaitai.Struct
	_f_fileTypeValid bool
	fileTypeValid bool
	_f_versionValid bool
	versionValid bool
}
func NewFac() *Fac {
	return &Fac{
	}
}

func (this Fac) IO_() *kaitai.Stream {
	return this._io
}

func (this *Fac) Read(io *kaitai.Stream, parent kaitai.Struct, root *Fac) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewGff()
	err = tmp1.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.GffData = tmp1
	return err
}

/**
 * Validates FAC file type
 */
func (this *Fac) FileTypeValid() (v bool, err error) {
	if (this._f_fileTypeValid) {
		return this.fileTypeValid, nil
	}
	this._f_fileTypeValid = true
	this.fileTypeValid = bool(this.GffData.Header.FileType == "FAC ")
	return this.fileTypeValid, nil
}

/**
 * Validates GFF version
 */
func (this *Fac) VersionValid() (v bool, err error) {
	if (this._f_versionValid) {
		return this.versionValid, nil
	}
	this._f_versionValid = true
	this.versionValid = bool( ((this.GffData.Header.FileVersion == "V3.2") || (this.GffData.Header.FileVersion == "V3.3") || (this.GffData.Header.FileVersion == "V4.0") || (this.GffData.Header.FileVersion == "V4.1")) )
	return this.versionValid, nil
}

/**
 * Complete GFF structure with "FAC " file type
 */
