// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * GAM (Game State) files are GFF-based format files that store game state information
 * including party members, global variables, game time, and time played.
 * 
 * This format inherits the complete GFF structure from gff.ksy and adds GAM-specific
 * validation and documentation.
 * 
 * GAM files are used by:
 * - Aurora Engine (Neverwinter Nights, Neverwinter Nights 2)
 * - Infinity Engine (Mass Effect, Dragon Age Origins, Dragon Age 2)
 * 
 * NOTE: Odyssey Engine (Knights of the Old Republic) does NOT use GAM format -
 * it uses NFO format for save games instead.
 * 
 * GAM Root Struct Fields:
 * - GameTimeHour, GameTimeMinute, GameTimeSecond, GameTimeMillisecond (Int32): Game time
 * - TimePlayed (Int32): Total playtime in seconds
 * - PartyList (List): Party member ResRefs
 * - GlobalBooleans, GlobalNumbers, GlobalStrings (Lists): Global variable storage
 * 
 * Aurora-specific: ModuleName, CurrentArea, PlayerCharacter
 * Infinity-specific: GameName, Chapter, JournalEntries
 * 
 * References:
 * - https://github.com/OldRepublicDevs/PyKotor/wiki/GFF-GAM.md
 * - https://github.com/OldRepublicDevs/PyKotor/wiki/GFF-File-Format.md
 */
type Gam struct {
	GffData *Gff
	_io *kaitai.Stream
	_root *Gam
	_parent kaitai.Struct
	_f_fileTypeValid bool
	fileTypeValid bool
	_f_versionValid bool
	versionValid bool
}
func NewGam() *Gam {
	return &Gam{
	}
}

func (this Gam) IO_() *kaitai.Stream {
	return this._io
}

func (this *Gam) Read(io *kaitai.Stream, parent kaitai.Struct, root *Gam) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewGff()
	err = tmp1.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.GffData = tmp1
	return err
}

/**
 * Validates that this is a GAM file (file type must be "GAM ")
 */
func (this *Gam) FileTypeValid() (v bool, err error) {
	if (this._f_fileTypeValid) {
		return this.fileTypeValid, nil
	}
	this._f_fileTypeValid = true
	this.fileTypeValid = bool(this.GffData.Header.FileType == "GAM ")
	return this.fileTypeValid, nil
}

/**
 * Validates GFF version is supported
 */
func (this *Gam) VersionValid() (v bool, err error) {
	if (this._f_versionValid) {
		return this.versionValid, nil
	}
	this._f_versionValid = true
	this.versionValid = bool( ((this.GffData.Header.FileVersion == "V3.2") || (this.GffData.Header.FileVersion == "V3.3") || (this.GffData.Header.FileVersion == "V4.0") || (this.GffData.Header.FileVersion == "V4.1")) )
	return this.versionValid, nil
}

/**
 * Complete GFF structure. GAM files use standard GFF format with "GAM " file type.
 * Access via: gff_data.header, gff_data.struct_array, gff_data.field_array, etc.
 */
