// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * Human-readable XML representation of GAM (Game State) binary files.
 * Uses GFF XML structure with <gff3> root element.
 * 
 * Binary format reference: ../gam/gam.ksy
 * 
 * References:
 * - PyKotor wiki (GFF-GAM.md, GFF-File-Format.md)
 */
type GamXml struct {
	XmlContent string
	_io *kaitai.Stream
	_root *GamXml
	_parent kaitai.Struct
}
func NewGamXml() *GamXml {
	return &GamXml{
	}
}

func (this GamXml) IO_() *kaitai.Stream {
	return this._io
}

func (this *GamXml) Read(io *kaitai.Stream, parent kaitai.Struct, root *GamXml) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.XmlContent = string(tmp1)
	return err
}

/**
 * XML document content as UTF-8 text
 */
