// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * GFF JSON format is a human-readable JSON representation of GFF (Generic File Format) binary files.
 * Provides easier editing and interoperability with modern tools than binary GFF format.
 * 
 * References:
 * - https://github.com/OldRepublicDevs/PyKotor/tree/master/Libraries/PyKotor/src/pykotor/resource/formats/gff/io_gff_xml.py
 */
type GffJson struct {
	JsonContent string
	_io *kaitai.Stream
	_root *GffJson
	_parent kaitai.Struct
}
func NewGffJson() *GffJson {
	return &GffJson{
	}
}

func (this GffJson) IO_() *kaitai.Stream {
	return this._io
}

func (this *GffJson) Read(io *kaitai.Stream, parent kaitai.Struct, root *GffJson) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.JsonContent = string(tmp1)
	return err
}

/**
 * JSON document content as UTF-8 text
 */
