// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * GFF XML format is a human-readable XML representation of GFF (Generic File Format) binary files.
 * Used by xoreos-tools and other modding tools for easier editing than binary GFF format.
 * 
 * The XML format represents the hierarchical GFF structure using XML elements:
 * - Root element: <gff3>
 * - Contains a <struct> element with id attribute
 * - Struct contains field elements (byte, uint32, exostring, locstring, resref, list, etc.)
 * - Each field has a label attribute
 * - Lists contain nested <struct> elements
 * 
 * References:
 * - https://github.com/OldRepublicDevs/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/resource/formats/gff/io_gff_xml.py
 * - https://github.com/xoreos/xoreos-tools/blob/master/src/xml/gffdumper.cpp
 * - https://github.com/xoreos/xoreos-tools/blob/master/src/xml/gffcreator.cpp
 */
type GffXml struct {
	XmlContent string
	_io *kaitai.Stream
	_root *GffXml
	_parent kaitai.Struct
}
func NewGffXml() *GffXml {
	return &GffXml{
	}
}

func (this GffXml) IO_() *kaitai.Stream {
	return this._io
}

func (this *GffXml) Read(io *kaitai.Stream, parent kaitai.Struct, root *GffXml) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.XmlContent = string(tmp1)
	return err
}

/**
 * XML document content as UTF-8 text.
 * Structure: <gff3><struct id="...">...</struct></gff3>
 * Note: Kaitai Struct has limited XML parsing capabilities. For full XML parsing,
 * use an XML parser library. This definition serves as a format identifier.
 */
