// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * GIT (Game Instance Template) files store dynamic area instance data including
 * placed creatures, placeables, doors, triggers, waypoints, sounds, stores, and encounters.
 * 
 * This format inherits the complete GFF structure from gff.ksy.
 * 
 * GIT Root Struct Fields:
 * - CreatureList (List): Placed creatures with positions, orientations
 * - DoorList (List): Placed doors with states, scripts
 * - PlaceableList (List): Placed placeables (chests, etc.)
 * - TriggerList (List): Trigger zones
 * - WaypointList (List): Navigation waypoints
 * - SoundList (List): Ambient sounds
 * - StoreList (List): Merchant shops
 * - EncounterList (List): Spawn encounters
 * - CameraList (List): Camera points
 * 
 * References:
 * - https://github.com/OldRepublicDevs/PyKotor/wiki/GFF-GIT.md
 */
type Git struct {
	GffData *Gff
	_io *kaitai.Stream
	_root *Git
	_parent kaitai.Struct
	_f_fileTypeValid bool
	fileTypeValid bool
	_f_versionValid bool
	versionValid bool
}
func NewGit() *Git {
	return &Git{
	}
}

func (this Git) IO_() *kaitai.Stream {
	return this._io
}

func (this *Git) Read(io *kaitai.Stream, parent kaitai.Struct, root *Git) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewGff()
	err = tmp1.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.GffData = tmp1
	return err
}
func (this *Git) FileTypeValid() (v bool, err error) {
	if (this._f_fileTypeValid) {
		return this.fileTypeValid, nil
	}
	this._f_fileTypeValid = true
	this.fileTypeValid = bool(this.GffData.Header.FileType == "GIT ")
	return this.fileTypeValid, nil
}
func (this *Git) VersionValid() (v bool, err error) {
	if (this._f_versionValid) {
		return this.versionValid, nil
	}
	this._f_versionValid = true
	this.versionValid = bool( ((this.GffData.Header.FileVersion == "V3.2") || (this.GffData.Header.FileVersion == "V3.3") || (this.GffData.Header.FileVersion == "V4.0") || (this.GffData.Header.FileVersion == "V4.1")) )
	return this.versionValid, nil
}
