// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * GUI (Graphical User Interface) files define UI layouts, controls, and properties.
 * 
 * This format inherits the complete GFF structure from gff.ksy.
 * 
 * GUI Root Struct Fields:
 * - CONTROLS (List): UI control elements (buttons, labels, listboxes, etc.)
 * - Each control contains:
 *   - CONTROLTYPE (Int32): Control type (button=4, label=5, listbox=9, etc.)
 *   - TAG (String): Control identifier
 *   - X, Y, WIDTH, HEIGHT (Int32): Position and size
 *   - TEXT (Struct): Text properties with STRREF, color, alignment
 *   - BORDER (Struct): Border properties
 *   - EXTENT (Struct): Dimensions
 *   - Various control-specific fields
 * 
 * References:
 * - https://github.com/OldRepublicDevs/PyKotor/wiki/GFF-GUI.md
 */
type Gui struct {
	GffData *Gff
	_io *kaitai.Stream
	_root *Gui
	_parent kaitai.Struct
	_f_fileTypeValid bool
	fileTypeValid bool
	_f_versionValid bool
	versionValid bool
}
func NewGui() *Gui {
	return &Gui{
	}
}

func (this Gui) IO_() *kaitai.Stream {
	return this._io
}

func (this *Gui) Read(io *kaitai.Stream, parent kaitai.Struct, root *Gui) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewGff()
	err = tmp1.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.GffData = tmp1
	return err
}
func (this *Gui) FileTypeValid() (v bool, err error) {
	if (this._f_fileTypeValid) {
		return this.fileTypeValid, nil
	}
	this._f_fileTypeValid = true
	this.fileTypeValid = bool(this.GffData.Header.FileType == "GUI ")
	return this.fileTypeValid, nil
}
func (this *Gui) VersionValid() (v bool, err error) {
	if (this._f_versionValid) {
		return this.versionValid, nil
	}
	this._f_versionValid = true
	this.versionValid = bool( ((this.GffData.Header.FileVersion == "V3.2") || (this.GffData.Header.FileVersion == "V3.3") || (this.GffData.Header.FileVersion == "V4.0") || (this.GffData.Header.FileVersion == "V4.1")) )
	return this.versionValid, nil
}
