// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * GVT (Global Variables Table) files store global game variables.
 * 
 * This format inherits the complete GFF structure from gff.ksy.
 * 
 * GVT Root Struct Fields:
 * - ValNumber, ValBoolean, ValString lists for different variable types
 */
type Gvt struct {
	GffData *Gff
	_io *kaitai.Stream
	_root *Gvt
	_parent kaitai.Struct
	_f_fileTypeValid bool
	fileTypeValid bool
	_f_versionValid bool
	versionValid bool
}
func NewGvt() *Gvt {
	return &Gvt{
	}
}

func (this Gvt) IO_() *kaitai.Stream {
	return this._io
}

func (this *Gvt) Read(io *kaitai.Stream, parent kaitai.Struct, root *Gvt) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewGff()
	err = tmp1.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.GffData = tmp1
	return err
}
func (this *Gvt) FileTypeValid() (v bool, err error) {
	if (this._f_fileTypeValid) {
		return this.fileTypeValid, nil
	}
	this._f_fileTypeValid = true
	this.fileTypeValid = bool(this.GffData.Header.FileType == "GVT ")
	return this.fileTypeValid, nil
}
func (this *Gvt) VersionValid() (v bool, err error) {
	if (this._f_versionValid) {
		return this.versionValid, nil
	}
	this._f_versionValid = true
	this.versionValid = bool( ((this.GffData.Header.FileVersion == "V3.2") || (this.GffData.Header.FileVersion == "V3.3") || (this.GffData.Header.FileVersion == "V4.0") || (this.GffData.Header.FileVersion == "V4.1")) )
	return this.versionValid, nil
}
