// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * Human-readable XML representation of GVT (Global Variables Table) binary files.
 * Uses GFF XML structure with <gff3> root element.
 * 
 * Binary format reference: ../gvt/gvt.ksy
 * 
 * References:
 * - PyKotor wiki (GFF-GVT.md, GFF-File-Format.md)
 */
type GvtXml struct {
	XmlContent string
	_io *kaitai.Stream
	_root *GvtXml
	_parent kaitai.Struct
}
func NewGvtXml() *GvtXml {
	return &GvtXml{
	}
}

func (this GvtXml) IO_() *kaitai.Stream {
	return this._io
}

func (this *GvtXml) Read(io *kaitai.Stream, parent kaitai.Struct, root *GvtXml) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.XmlContent = string(tmp1)
	return err
}

/**
 * XML document content as UTF-8 text
 */
