// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * ITP XML format is a human-readable XML representation of ITP (Palette) binary files.
 * ITP files use GFF format (FileType "ITP " in GFF header).
 * Uses GFF XML structure with root element <gff3> containing <struct> elements.
 * Each field has a label attribute and appropriate type element (byte, uint32, exostring, etc.).
 * 
 * References:
 * - https://github.com/OldRepublicDevs/PyKotor/tree/master/Libraries/PyKotor/src/pykotor/resource/formats/itp/itp.py
 * - https://github.com/OldRepublicDevs/PyKotor/tree/master/Libraries/PyKotor/src/pykotor/resource/formats/gff/io_gff_xml.py
 * - https://github.com/seedhartha/reone/tree/master/src/libs/resource/parser/gff/itp.cpp
 * - https://github.com/OldRepublicDevs/PyKotor/wiki/GFF-File-Format.md
 * - https://github.com/OldRepublicDevs/PyKotor/wiki/ITP-File-Format.md
 * - https://github.com/xoreos/xoreos/tree/master/src/aurora/gff3file.cpp
 */
type ItpXml struct {
	XmlContent string
	_io *kaitai.Stream
	_root *ItpXml
	_parent kaitai.Struct
}
func NewItpXml() *ItpXml {
	return &ItpXml{
	}
}

func (this ItpXml) IO_() *kaitai.Stream {
	return this._io
}

func (this *ItpXml) Read(io *kaitai.Stream, parent kaitai.Struct, root *ItpXml) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.XmlContent = string(tmp1)
	return err
}

/**
 * XML document content as UTF-8 text
 */
