// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * JRL (Journal) files store quest journal entries and categories.
 * 
 * This format inherits the complete GFF structure from gff.ksy.
 * 
 * JRL Root Struct Fields:
 * - Categories (List): Journal categories
 * - Each category contains quest entries with text, states, priorities
 * 
 * References:
 * - https://github.com/OldRepublicDevs/PyKotor/wiki/GFF-JRL.md
 */
type Jrl struct {
	GffData *Gff
	_io *kaitai.Stream
	_root *Jrl
	_parent kaitai.Struct
	_f_fileTypeValid bool
	fileTypeValid bool
	_f_versionValid bool
	versionValid bool
}
func NewJrl() *Jrl {
	return &Jrl{
	}
}

func (this Jrl) IO_() *kaitai.Stream {
	return this._io
}

func (this *Jrl) Read(io *kaitai.Stream, parent kaitai.Struct, root *Jrl) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewGff()
	err = tmp1.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.GffData = tmp1
	return err
}
func (this *Jrl) FileTypeValid() (v bool, err error) {
	if (this._f_fileTypeValid) {
		return this.fileTypeValid, nil
	}
	this._f_fileTypeValid = true
	this.fileTypeValid = bool(this.GffData.Header.FileType == "JRL ")
	return this.fileTypeValid, nil
}
func (this *Jrl) VersionValid() (v bool, err error) {
	if (this._f_versionValid) {
		return this.versionValid, nil
	}
	this._f_versionValid = true
	this.versionValid = bool( ((this.GffData.Header.FileVersion == "V3.2") || (this.GffData.Header.FileVersion == "V3.3") || (this.GffData.Header.FileVersion == "V4.0") || (this.GffData.Header.FileVersion == "V4.1")) )
	return this.versionValid, nil
}
