// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * LIP (LIP Synchronization) files drive mouth animation for voiced dialogue in BioWare games.
 * Each file contains a compact series of keyframes that map timestamps to discrete viseme
 * (mouth shape) indices so that the engine can interpolate character lip movement while
 * playing the companion WAV audio line.
 * 
 * LIP files are always binary and contain only animation data. They are paired with WAV
 * voice-over resources of identical duration; the LIP length field must match the WAV
 * playback time for glitch-free animation.
 * 
 * Keyframes are sorted chronologically and store a timestamp (float seconds) plus a
 * 1-byte viseme index (0-15). The format uses the 16-shape Preston Blair phoneme set.
 * 
 * References:
 * - https://github.com/OldRepublicDevs/PyKotor/wiki/LIP-File-Format.md
 * - https://github.com/seedhartha/reone/blob/master/src/libs/graphics/format/lipreader.cpp:27-42
 * - https://github.com/xoreos/xoreos/blob/master/src/graphics/aurora/lipfile.cpp
 * - https://github.com/KotOR-Community-Patches/KotOR.js/blob/master/src/resource/LIPObject.ts:93-146
 */

type Lip_LipShapes int
const (
	Lip_LipShapes__Neutral Lip_LipShapes = 0
	Lip_LipShapes__Ee Lip_LipShapes = 1
	Lip_LipShapes__Eh Lip_LipShapes = 2
	Lip_LipShapes__Ah Lip_LipShapes = 3
	Lip_LipShapes__Oh Lip_LipShapes = 4
	Lip_LipShapes__Ooh Lip_LipShapes = 5
	Lip_LipShapes__Y Lip_LipShapes = 6
	Lip_LipShapes__Sts Lip_LipShapes = 7
	Lip_LipShapes__Fv Lip_LipShapes = 8
	Lip_LipShapes__Ng Lip_LipShapes = 9
	Lip_LipShapes__Th Lip_LipShapes = 10
	Lip_LipShapes__Mpb Lip_LipShapes = 11
	Lip_LipShapes__Td Lip_LipShapes = 12
	Lip_LipShapes__Sh Lip_LipShapes = 13
	Lip_LipShapes__L Lip_LipShapes = 14
	Lip_LipShapes__Kg Lip_LipShapes = 15
)
var values_Lip_LipShapes = map[Lip_LipShapes]struct{}{0: {}, 1: {}, 2: {}, 3: {}, 4: {}, 5: {}, 6: {}, 7: {}, 8: {}, 9: {}, 10: {}, 11: {}, 12: {}, 13: {}, 14: {}, 15: {}}
func (v Lip_LipShapes) isDefined() bool {
	_, ok := values_Lip_LipShapes[v]
	return ok
}
type Lip struct {
	FileType string
	FileVersion string
	Length float32
	NumKeyframes uint32
	Keyframes []*Lip_KeyframeEntry
	_io *kaitai.Stream
	_root *Lip
	_parent kaitai.Struct
}
func NewLip() *Lip {
	return &Lip{
	}
}

func (this Lip) IO_() *kaitai.Stream {
	return this._io
}

func (this *Lip) Read(io *kaitai.Stream, parent kaitai.Struct, root *Lip) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.FileType = string(tmp1)
	tmp2, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp2 = tmp2
	this.FileVersion = string(tmp2)
	tmp3, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.Length = float32(tmp3)
	tmp4, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumKeyframes = uint32(tmp4)
	for i := 0; i < int(this.NumKeyframes); i++ {
		_ = i
		tmp5 := NewLip_KeyframeEntry()
		err = tmp5.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Keyframes = append(this.Keyframes, tmp5)
	}
	return err
}

/**
 * File type signature. Must be "LIP " (space-padded) for LIP files.
 */

/**
 * File format version. Must be "V1.0" for LIP files.
 */

/**
 * Duration in seconds. Must equal the paired WAV file playback time for
 * glitch-free animation. This is the total length of the lip sync animation.
 */

/**
 * Number of keyframes immediately following. Each keyframe contains a timestamp
 * and a viseme shape index. Keyframes should be sorted ascending by timestamp.
 */

/**
 * Array of keyframe entries. Each entry maps a timestamp to a mouth shape.
 * Entries must be stored in chronological order (ascending by timestamp).
 */

/**
 * A single keyframe entry mapping a timestamp to a viseme (mouth shape).
 * Keyframes are used by the engine to interpolate between mouth shapes during
 * audio playback to create lip sync animation.
 */
type Lip_KeyframeEntry struct {
	Timestamp float32
	Shape Lip_LipShapes
	_io *kaitai.Stream
	_root *Lip
	_parent *Lip
}
func NewLip_KeyframeEntry() *Lip_KeyframeEntry {
	return &Lip_KeyframeEntry{
	}
}

func (this Lip_KeyframeEntry) IO_() *kaitai.Stream {
	return this._io
}

func (this *Lip_KeyframeEntry) Read(io *kaitai.Stream, parent *Lip, root *Lip) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp6, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.Timestamp = float32(tmp6)
	tmp7, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Shape = Lip_LipShapes(tmp7)
	return err
}

/**
 * Seconds from animation start. Must be >= 0 and <= length.
 * Keyframes should be sorted ascending by timestamp.
 */

/**
 * Viseme index (0-15) indicating which mouth shape to use at this timestamp.
 * Uses the 16-shape Preston Blair phoneme set. See lip_shapes enum for details.
 */
