// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * LIP XML format is a human-readable XML representation of LIP (Lipsync) binary files.
 * Provides easier editing than binary LIP format.
 * 
 * References:
 * - https://github.com/OldRepublicDevs/PyKotor/tree/master/Libraries/PyKotor/src/pykotor/resource/formats/lip/lip.py
 * - https://github.com/OldRepublicDevs/PyKotor/tree/master/Libraries/PyKotor/src/pykotor/resource/formats/lip/io_lip_xml.py
 * - https://github.com/seedhartha/reone/tree/master/src/libs/graphics/format/lipreader.cpp
 * - https://github.com/OldRepublicDevs/PyKotor/wiki/LIP-File-Format.md
 * - https://github.com/xoreos/xoreos/tree/master/src/graphics/aurora/lipfile.cpp
 * 
 * - ../GFF/GFF
 * - ../GFF/XML/GFF_XML
 * - ../LIP/LIP
 */
type LipXml struct {
	XmlContent string
	_io *kaitai.Stream
	_root *LipXml
	_parent kaitai.Struct
}
func NewLipXml() *LipXml {
	return &LipXml{
	}
}

func (this LipXml) IO_() *kaitai.Stream {
	return this._io
}

func (this *LipXml) Read(io *kaitai.Stream, parent kaitai.Struct, root *LipXml) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.XmlContent = string(tmp1)
	return err
}

/**
 * XML document content as UTF-8 text
 */
