// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * LIP JSON format is a human-readable JSON representation of LIP (Lipsync) binary files.
 * Provides easier editing than binary LIP format.
 * 
 * References:
 * - https://github.com/OldRepublicDevs/PyKotor/tree/master/Libraries/PyKotor/src/pykotor/resource/formats/lip/io_lip_xml.py
 */
type LipJson struct {
	JsonContent string
	_io *kaitai.Stream
	_root *LipJson
	_parent kaitai.Struct
}
func NewLipJson() *LipJson {
	return &LipJson{
	}
}

func (this LipJson) IO_() *kaitai.Stream {
	return this._io
}

func (this *LipJson) Read(io *kaitai.Stream, parent kaitai.Struct, root *LipJson) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.JsonContent = string(tmp1)
	return err
}

/**
 * JSON document content as UTF-8 text
 */
