// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type NcsMinimal struct {
	FileType string
	FileVersion string
	SizeMarker uint8
	TotalFileSize uint32
	Instructions []*NcsMinimal_Instruction
	_io *kaitai.Stream
	_root *NcsMinimal
	_parent kaitai.Struct
}
func NewNcsMinimal() *NcsMinimal {
	return &NcsMinimal{
	}
}

func (this NcsMinimal) IO_() *kaitai.Stream {
	return this._io
}

func (this *NcsMinimal) Read(io *kaitai.Stream, parent kaitai.Struct, root *NcsMinimal) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.FileType = string(tmp1)
	tmp2, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp2 = tmp2
	this.FileVersion = string(tmp2)
	tmp3, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.SizeMarker = tmp3
	tmp4, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.TotalFileSize = uint32(tmp4)
	for i := 1;; i++ {
		tmp5 := NewNcsMinimal_Instruction()
		err = tmp5.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		_it := tmp5
		this.Instructions = append(this.Instructions, _it)
		tmp6, err := this._io.Pos()
		if err != nil {
			return err
		}
		if tmp6 >= this._root.TotalFileSize {
			break
		}
	}
	return err
}
type NcsMinimal_Instruction struct {
	Bytecode uint8
	Qualifier uint8
	_io *kaitai.Stream
	_root *NcsMinimal
	_parent *NcsMinimal
}
func NewNcsMinimal_Instruction() *NcsMinimal_Instruction {
	return &NcsMinimal_Instruction{
	}
}

func (this NcsMinimal_Instruction) IO_() *kaitai.Stream {
	return this._io
}

func (this *NcsMinimal_Instruction) Read(io *kaitai.Stream, parent *NcsMinimal, root *NcsMinimal) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp7, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Bytecode = tmp7
	tmp8, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Qualifier = tmp8
	return err
}
