// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * NFO (Module Info) files store save game module information for KotOR.
 * 
 * This format inherits the complete GFF structure from gff.ksy.
 * 
 * Note: This is different from IFO files. NFO is used in save games,
 * while IFO is used in module definitions.
 */
type Nfo struct {
	GffData *Gff
	_io *kaitai.Stream
	_root *Nfo
	_parent kaitai.Struct
	_f_fileTypeValid bool
	fileTypeValid bool
	_f_versionValid bool
	versionValid bool
}
func NewNfo() *Nfo {
	return &Nfo{
	}
}

func (this Nfo) IO_() *kaitai.Stream {
	return this._io
}

func (this *Nfo) Read(io *kaitai.Stream, parent kaitai.Struct, root *Nfo) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewGff()
	err = tmp1.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.GffData = tmp1
	return err
}
func (this *Nfo) FileTypeValid() (v bool, err error) {
	if (this._f_fileTypeValid) {
		return this.fileTypeValid, nil
	}
	this._f_fileTypeValid = true
	this.fileTypeValid = bool(this.GffData.Header.FileType == "NFO ")
	return this.fileTypeValid, nil
}
func (this *Nfo) VersionValid() (v bool, err error) {
	if (this._f_versionValid) {
		return this.versionValid, nil
	}
	this._f_versionValid = true
	this.versionValid = bool( ((this.GffData.Header.FileVersion == "V3.2") || (this.GffData.Header.FileVersion == "V3.3") || (this.GffData.Header.FileVersion == "V4.0") || (this.GffData.Header.FileVersion == "V4.1")) )
	return this.versionValid, nil
}
