// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * PTH (Path/Pathfinding) files store pathfinding waypoint graphs for AI navigation.
 * 
 * This format inherits the complete GFF structure from gff.ksy.
 * 
 * PTH Root Struct Fields:
 * - Path_Points (List): Waypoint positions (X, Y coordinates)
 * - Connections (List): Connections between waypoints
 * 
 * References:
 * - https://github.com/OldRepublicDevs/PyKotor/wiki/GFF-PTH.md
 * - https://github.com/OldRepublicDevs/PyKotor/wiki/GFF-File-Format.md
 * - https://github.com/OldRepublicDevs/PyKotor/blob/master/Libraries/PyKotor/src/pykotor/resource/generics/pth.py
 */
type Pth struct {
	GffData *Gff
	_io *kaitai.Stream
	_root *Pth
	_parent kaitai.Struct
	_f_fileTypeValid bool
	fileTypeValid bool
	_f_versionValid bool
	versionValid bool
}
func NewPth() *Pth {
	return &Pth{
	}
}

func (this Pth) IO_() *kaitai.Stream {
	return this._io
}

func (this *Pth) Read(io *kaitai.Stream, parent kaitai.Struct, root *Pth) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewGff()
	err = tmp1.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.GffData = tmp1
	return err
}
func (this *Pth) FileTypeValid() (v bool, err error) {
	if (this._f_fileTypeValid) {
		return this.fileTypeValid, nil
	}
	this._f_fileTypeValid = true
	this.fileTypeValid = bool(this.GffData.Header.FileType == "PTH ")
	return this.fileTypeValid, nil
}
func (this *Pth) VersionValid() (v bool, err error) {
	if (this._f_versionValid) {
		return this.versionValid, nil
	}
	this._f_versionValid = true
	this.versionValid = bool( ((this.GffData.Header.FileVersion == "V3.2") || (this.GffData.Header.FileVersion == "V3.3") || (this.GffData.Header.FileVersion == "V4.0") || (this.GffData.Header.FileVersion == "V4.1")) )
	return this.versionValid, nil
}
