// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * RES XML format is a human-readable XML representation of RES (Save Data) binary files.
 * Uses GFF XML structure with root element <gff3> containing <struct> elements.
 * Each field has a label attribute and appropriate type element (byte, uint32, exostring, etc.).
 * 
 * References:
 * - https://github.com/OldRepublicDevs/PyKotor/tree/master/Libraries/PyKotor/src/pykotor/resource/formats/gff/io_gff_xml.py
 */
type ResXml struct {
	XmlContent string
	_io *kaitai.Stream
	_root *ResXml
	_parent kaitai.Struct
}
func NewResXml() *ResXml {
	return &ResXml{
	}
}

func (this ResXml) IO_() *kaitai.Stream {
	return this._io
}

func (this *ResXml) Read(io *kaitai.Stream, parent kaitai.Struct, root *ResXml) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.XmlContent = string(tmp1)
	return err
}

/**
 * XML document content as UTF-8 text
 */
