// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * SSF XML format is a human-readable XML representation of SSF (Soundset) binary files.
 * Provides easier editing than binary SSF format.
 * 
 * References:
 * - https://github.com/OldRepublicDevs/PyKotor/tree/master/Libraries/PyKotor/src/pykotor/resource/formats/ssf/ssf.py
 * - https://github.com/OldRepublicDevs/PyKotor/tree/master/Libraries/PyKotor/src/pykotor/resource/formats/ssf/io_ssf_xml.py
 * - https://github.com/seedhartha/reone/tree/master/src/libs/resource/parser/ssf.cpp
 * - https://github.com/OldRepublicDevs/PyKotor/wiki/SSF-File-Format.md
 * - https://github.com/xoreos/xoreos/tree/master/src/aurora/ssffile.cpp
 */
type SsfXml struct {
	XmlContent string
	_io *kaitai.Stream
	_root *SsfXml
	_parent kaitai.Struct
}
func NewSsfXml() *SsfXml {
	return &SsfXml{
	}
}

func (this SsfXml) IO_() *kaitai.Stream {
	return this._io
}

func (this *SsfXml) Read(io *kaitai.Stream, parent kaitai.Struct, root *SsfXml) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.XmlContent = string(tmp1)
	return err
}

/**
 * XML document content as UTF-8 text
 */
