// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * TLK JSON format is a human-readable JSON representation of TLK (Talk Table) binary files.
 * Provides easier editing and translation than binary TLK format.
 * 
 * References:
 * - https://github.com/OldRepublicDevs/PyKotor/tree/master/Libraries/PyKotor/src/pykotor/resource/formats/tlk/io_tlk_xml.py
 */
type TlkJson struct {
	JsonContent string
	_io *kaitai.Stream
	_root *TlkJson
	_parent kaitai.Struct
}
func NewTlkJson() *TlkJson {
	return &TlkJson{
	}
}

func (this TlkJson) IO_() *kaitai.Stream {
	return this._io
}

func (this *TlkJson) Read(io *kaitai.Stream, parent kaitai.Struct, root *TlkJson) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.JsonContent = string(tmp1)
	return err
}

/**
 * JSON document content as UTF-8 text
 */
