// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * TwoDA CSV format is a human-readable CSV (Comma-Separated Values) representation of TwoDA files.
 * Provides easier editing in spreadsheet applications than binary TwoDA format.
 * 
 * Each row represents a data row, with the first row containing column headers.
 * 
 * References:
 * - https://github.com/OldRepublicDevs/PyKotor/tree/master/Libraries/PyKotor/src/pykotor/resource/formats/twoda/io_twoda.py
 */
type TwodaCsv struct {
	CsvContent string
	_io *kaitai.Stream
	_root *TwodaCsv
	_parent kaitai.Struct
}
func NewTwodaCsv() *TwodaCsv {
	return &TwodaCsv{
	}
}

func (this TwodaCsv) IO_() *kaitai.Stream {
	return this._io
}

func (this *TwodaCsv) Read(io *kaitai.Stream, parent kaitai.Struct, root *TwodaCsv) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.CsvContent = string(tmp1)
	return err
}

/**
 * CSV text content with rows separated by newlines and columns by commas
 */
