// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * TwoDA JSON format is a human-readable JSON representation of TwoDA files.
 * Provides easier editing and interoperability with modern tools than binary TwoDA format.
 * 
 * References:
 * - https://github.com/OldRepublicDevs/PyKotor/tree/master/Libraries/PyKotor/src/pykotor/resource/formats/twoda/io_twoda.py
 */
type TwodaJson struct {
	JsonContent string
	_io *kaitai.Stream
	_root *TwodaJson
	_parent kaitai.Struct
}
func NewTwodaJson() *TwodaJson {
	return &TwodaJson{
	}
}

func (this TwodaJson) IO_() *kaitai.Stream {
	return this._io
}

func (this *TwodaJson) Read(io *kaitai.Stream, parent kaitai.Struct, root *TwodaJson) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.JsonContent = string(tmp1)
	return err
}

/**
 * JSON document content as UTF-8 text
 */
