// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * UTD (Door Template) files define door properties, scripts, and behavior.
 * 
 * This format inherits the complete GFF structure from gff.ksy.
 * 
 * UTD Root Struct Fields:
 * - TemplateResRef (ResRef): Blueprint identifier
 * - Tag (String): Instance identifier
 * - LocalizedName (LocalizedString): Door name
 * - Appearance (UInt32): Door appearance ID
 * - Locked, KeyRequired, Trap, Faction (various): Door state/behavior
 * - Script hooks: OnClick, OnClosed, OnDamaged, OnDeath, OnDisarm, OnFailToOpen, etc.
 */
type Utd struct {
	GffData *Gff
	_io *kaitai.Stream
	_root *Utd
	_parent kaitai.Struct
	_f_fileTypeValid bool
	fileTypeValid bool
	_f_versionValid bool
	versionValid bool
}
func NewUtd() *Utd {
	return &Utd{
	}
}

func (this Utd) IO_() *kaitai.Stream {
	return this._io
}

func (this *Utd) Read(io *kaitai.Stream, parent kaitai.Struct, root *Utd) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewGff()
	err = tmp1.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.GffData = tmp1
	return err
}
func (this *Utd) FileTypeValid() (v bool, err error) {
	if (this._f_fileTypeValid) {
		return this.fileTypeValid, nil
	}
	this._f_fileTypeValid = true
	this.fileTypeValid = bool(this.GffData.Header.FileType == "UTD ")
	return this.fileTypeValid, nil
}
func (this *Utd) VersionValid() (v bool, err error) {
	if (this._f_versionValid) {
		return this.versionValid, nil
	}
	this._f_versionValid = true
	this.versionValid = bool( ((this.GffData.Header.FileVersion == "V3.2") || (this.GffData.Header.FileVersion == "V3.3")) )
	return this.versionValid, nil
}
