// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * UTE (Encounter Template) files define spawn encounters with creature lists and probabilities.
 * 
 * This format inherits the complete GFF structure from gff.ksy.
 * 
 * UTE Root Struct Fields:
 * - TemplateResRef (ResRef): Blueprint identifier
 * - Tag (String): Instance identifier
 * - LocalizedName (LocalizedString): Encounter name
 * - CreatureList (List): Creatures to spawn with probabilities
 * - Difficulty, MaxCreatures, RecCreatures, SpawnOption: Spawn behavior
 * - Script hooks: OnEntered, OnExhausted, OnExit, OnHeartbeat, OnUserDefined
 */
type Ute struct {
	GffData *Gff
	_io *kaitai.Stream
	_root *Ute
	_parent kaitai.Struct
	_f_fileTypeValid bool
	fileTypeValid bool
	_f_versionValid bool
	versionValid bool
}
func NewUte() *Ute {
	return &Ute{
	}
}

func (this Ute) IO_() *kaitai.Stream {
	return this._io
}

func (this *Ute) Read(io *kaitai.Stream, parent kaitai.Struct, root *Ute) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewGff()
	err = tmp1.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.GffData = tmp1
	return err
}
func (this *Ute) FileTypeValid() (v bool, err error) {
	if (this._f_fileTypeValid) {
		return this.fileTypeValid, nil
	}
	this._f_fileTypeValid = true
	this.fileTypeValid = bool(this.GffData.Header.FileType == "UTE ")
	return this.fileTypeValid, nil
}
func (this *Ute) VersionValid() (v bool, err error) {
	if (this._f_versionValid) {
		return this.versionValid, nil
	}
	this._f_versionValid = true
	this.versionValid = bool( ((this.GffData.Header.FileVersion == "V3.2") || (this.GffData.Header.FileVersion == "V3.3")) )
	return this.versionValid, nil
}
