// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * Human-readable XML representation of UTE (Encounter Template) binary files.
 * Uses GFF XML structure with <gff3> root element.
 * 
 * Binary format reference: ../ute/ute.ksy
 * 
 * References:
 * - PyKotor wiki (GFF-UTE.md, GFF-File-Format.md)
 */
type UteXml struct {
	XmlContent string
	_io *kaitai.Stream
	_root *UteXml
	_parent kaitai.Struct
}
func NewUteXml() *UteXml {
	return &UteXml{
	}
}

func (this UteXml) IO_() *kaitai.Stream {
	return this._io
}

func (this *UteXml) Read(io *kaitai.Stream, parent kaitai.Struct, root *UteXml) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.XmlContent = string(tmp1)
	return err
}

/**
 * XML document content as UTF-8 text
 */
