// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * UTI (Item Template) files define item properties, stats, and behavior.
 * 
 * This format inherits the complete GFF structure from gff.ksy.
 * 
 * UTI Root Struct Fields:
 * - TemplateResRef (ResRef): Blueprint identifier
 * - Tag (String): Instance identifier
 * - LocalizedName (LocalizedString): Item name
 * - Description (LocalizedString): Item description
 * - BaseItem (Int32): Base item type (baseitems.2da)
 * - Cost, StackSize, Charges: Item economics
 * - ModelVariation, TextureVar, BodyVariation: Item appearance
 * - PropertiesList (List): Item properties (damage, attack bonus, etc.)
 */
type Uti struct {
	GffData *Gff
	_io *kaitai.Stream
	_root *Uti
	_parent kaitai.Struct
	_f_fileTypeValid bool
	fileTypeValid bool
	_f_versionValid bool
	versionValid bool
}
func NewUti() *Uti {
	return &Uti{
	}
}

func (this Uti) IO_() *kaitai.Stream {
	return this._io
}

func (this *Uti) Read(io *kaitai.Stream, parent kaitai.Struct, root *Uti) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewGff()
	err = tmp1.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.GffData = tmp1
	return err
}
func (this *Uti) FileTypeValid() (v bool, err error) {
	if (this._f_fileTypeValid) {
		return this.fileTypeValid, nil
	}
	this._f_fileTypeValid = true
	this.fileTypeValid = bool(this.GffData.Header.FileType == "UTI ")
	return this.fileTypeValid, nil
}
func (this *Uti) VersionValid() (v bool, err error) {
	if (this._f_versionValid) {
		return this.versionValid, nil
	}
	this._f_versionValid = true
	this.versionValid = bool( ((this.GffData.Header.FileVersion == "V3.2") || (this.GffData.Header.FileVersion == "V3.3")) )
	return this.versionValid, nil
}
