// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * Human-readable XML representation of UTI (Item Template) binary files.
 * Uses GFF XML structure with <gff3> root element.
 * 
 * Binary format reference: ../uti/uti.ksy
 * 
 * References:
 * - PyKotor wiki (GFF-UTI.md, GFF-File-Format.md)
 */
type UtiXml struct {
	XmlContent string
	_io *kaitai.Stream
	_root *UtiXml
	_parent kaitai.Struct
}
func NewUtiXml() *UtiXml {
	return &UtiXml{
	}
}

func (this UtiXml) IO_() *kaitai.Stream {
	return this._io
}

func (this *UtiXml) Read(io *kaitai.Stream, parent kaitai.Struct, root *UtiXml) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.XmlContent = string(tmp1)
	return err
}

/**
 * XML document content as UTF-8 text
 */
