// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * Human-readable XML representation of UTM (Store/Merchant Template) binary files.
 * Uses GFF XML structure with <gff3> root element.
 * 
 * Binary format reference: ../utm/utm.ksy
 * 
 * References:
 * - PyKotor wiki (GFF-UTM.md, GFF-File-Format.md)
 */
type UtmXml struct {
	XmlContent string
	_io *kaitai.Stream
	_root *UtmXml
	_parent kaitai.Struct
}
func NewUtmXml() *UtmXml {
	return &UtmXml{
	}
}

func (this UtmXml) IO_() *kaitai.Stream {
	return this._io
}

func (this *UtmXml) Read(io *kaitai.Stream, parent kaitai.Struct, root *UtmXml) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.XmlContent = string(tmp1)
	return err
}

/**
 * XML document content as UTF-8 text
 */
