// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * UTP (Placeable Template) files define placeable objects (containers, furniture, etc.).
 * 
 * This format inherits the complete GFF structure from gff.ksy.
 * 
 * UTP Root Struct Fields:
 * - TemplateResRef (ResRef): Blueprint identifier
 * - Tag (String): Instance identifier
 * - LocalizedName (LocalizedString): Placeable name
 * - Appearance (UInt32): Placeable appearance ID
 * - HasInventory, ItemList (List): Container contents
 * - Locked, KeyRequired, Trap: Security settings
 * - Script hooks: OnClick, OnClosed, OnDamaged, OnDeath, OnDisarm, OnHeartbeat, etc.
 */
type Utp struct {
	GffData *Gff
	_io *kaitai.Stream
	_root *Utp
	_parent kaitai.Struct
	_f_fileTypeValid bool
	fileTypeValid bool
	_f_versionValid bool
	versionValid bool
}
func NewUtp() *Utp {
	return &Utp{
	}
}

func (this Utp) IO_() *kaitai.Stream {
	return this._io
}

func (this *Utp) Read(io *kaitai.Stream, parent kaitai.Struct, root *Utp) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewGff()
	err = tmp1.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.GffData = tmp1
	return err
}
func (this *Utp) FileTypeValid() (v bool, err error) {
	if (this._f_fileTypeValid) {
		return this.fileTypeValid, nil
	}
	this._f_fileTypeValid = true
	this.fileTypeValid = bool(this.GffData.Header.FileType == "UTP ")
	return this.fileTypeValid, nil
}
func (this *Utp) VersionValid() (v bool, err error) {
	if (this._f_versionValid) {
		return this.versionValid, nil
	}
	this._f_versionValid = true
	this.versionValid = bool( ((this.GffData.Header.FileVersion == "V3.2") || (this.GffData.Header.FileVersion == "V3.3")) )
	return this.versionValid, nil
}
