// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * UTS (Sound Template) files define ambient sound sources and properties.
 * 
 * This format inherits the complete GFF structure from gff.ksy.
 * 
 * UTS Root Struct Fields:
 * - TemplateResRef (ResRef): Blueprint identifier
 * - Tag (String): Instance identifier
 * - LocalizedName (LocalizedString): Sound name
 * - Sounds (List): Sound file references
 * - Volume, MaxDistance, MinDistance: Audio properties
 * - Looping, Random, Positional: Sound behavior
 */
type Uts struct {
	GffData *Gff
	_io *kaitai.Stream
	_root *Uts
	_parent kaitai.Struct
	_f_fileTypeValid bool
	fileTypeValid bool
	_f_versionValid bool
	versionValid bool
}
func NewUts() *Uts {
	return &Uts{
	}
}

func (this Uts) IO_() *kaitai.Stream {
	return this._io
}

func (this *Uts) Read(io *kaitai.Stream, parent kaitai.Struct, root *Uts) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewGff()
	err = tmp1.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.GffData = tmp1
	return err
}
func (this *Uts) FileTypeValid() (v bool, err error) {
	if (this._f_fileTypeValid) {
		return this.fileTypeValid, nil
	}
	this._f_fileTypeValid = true
	this.fileTypeValid = bool(this.GffData.Header.FileType == "UTS ")
	return this.fileTypeValid, nil
}
func (this *Uts) VersionValid() (v bool, err error) {
	if (this._f_versionValid) {
		return this.versionValid, nil
	}
	this._f_versionValid = true
	this.versionValid = bool( ((this.GffData.Header.FileVersion == "V3.2") || (this.GffData.Header.FileVersion == "V3.3")) )
	return this.versionValid, nil
}
