// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * UTT (Trigger Template) files define trigger zones and their properties.
 * 
 * This format inherits the complete GFF structure from gff.ksy.
 * 
 * UTT Root Struct Fields:
 * - TemplateResRef (ResRef): Blueprint identifier
 * - Tag (String): Instance identifier
 * - LocalizedName (LocalizedString): Trigger name
 * - Geometry (List): Trigger zone vertices
 * - TriggerType, Cursor, Faction: Trigger behavior
 * - Script hooks: OnClick, OnDisarm, OnHeartbeat, OnTrapTriggered, OnUserDefined
 */
type Utt struct {
	GffData *Gff
	_io *kaitai.Stream
	_root *Utt
	_parent kaitai.Struct
	_f_fileTypeValid bool
	fileTypeValid bool
	_f_versionValid bool
	versionValid bool
}
func NewUtt() *Utt {
	return &Utt{
	}
}

func (this Utt) IO_() *kaitai.Stream {
	return this._io
}

func (this *Utt) Read(io *kaitai.Stream, parent kaitai.Struct, root *Utt) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewGff()
	err = tmp1.Read(this._io, nil, nil)
	if err != nil {
		return err
	}
	this.GffData = tmp1
	return err
}
func (this *Utt) FileTypeValid() (v bool, err error) {
	if (this._f_fileTypeValid) {
		return this.fileTypeValid, nil
	}
	this._f_fileTypeValid = true
	this.fileTypeValid = bool(this.GffData.Header.FileType == "UTT ")
	return this.fileTypeValid, nil
}
func (this *Utt) VersionValid() (v bool, err error) {
	if (this._f_versionValid) {
		return this.versionValid, nil
	}
	this._f_versionValid = true
	this.versionValid = bool( ((this.GffData.Header.FileVersion == "V3.2") || (this.GffData.Header.FileVersion == "V3.3")) )
	return this.versionValid, nil
}
