// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"


/**
 * Human-readable XML representation of UTT (Trigger Template) binary files.
 * Uses GFF XML structure with <gff3> root element.
 * 
 * Binary format reference: ../utt/utt.ksy
 * 
 * References:
 * - PyKotor wiki (GFF-UTT.md, GFF-File-Format.md)
 */
type UttXml struct {
	XmlContent string
	_io *kaitai.Stream
	_root *UttXml
	_parent kaitai.Struct
}
func NewUttXml() *UttXml {
	return &UttXml{
	}
}

func (this UttXml) IO_() *kaitai.Stream {
	return this._io
}

func (this *UttXml) Read(io *kaitai.Stream, parent kaitai.Struct, root *UttXml) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp1 = tmp1
	this.XmlContent = string(tmp1)
	return err
}

/**
 * XML document content as UTF-8 text
 */
